import rock from './Boundary.png';
import space from './space.jpg';
import down from './down.png'
import up from './up.png'
import finish from './finishline.gif'
import player from './components/Player.jsx';


export const levels = [
        [down,space,space,space,space,
        rock,space,rock,rock,space,
        space,space,rock,rock,space,
        rock,rock,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,space,rock,
        space,rock,space,space,rock,
        space,rock,rock,space,space,
        space,rock,rock,rock,space,
        space,rock,rock,space,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,rock,
        space,space,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        rock,rock,space,rock,space,
        space,space,rock,space,space,
        rock,space,space,space,rock,
        rock,rock,space,rock,rock,
        space,space,'finish',space,space],

        [down,rock,rock,rock,rock,
        space,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,space,space,rock,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,rock,space,space,
        space,rock,rock,rock,space,
        space,space,rock,rock,space,
        rock,space,rock,space,space,
        rock,space,rock,rock,space,
        rock,space,space,rock,space,
        space,space,rock,rock,space,
        space,space,space,rock,space,
        rock,rock,space,rock,space,
        rock,rock,space,rock,space,
        rock,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,space,
        space,rock,rock,space,space,
        space,rock,space,space,space,
        rock,space,space,rock,space,
        space,space,rock,space,space,
        space,rock,rock,'finish',rock],

        [space,space,space,space,down,
        space,rock,rock,rock,rock,
        space,space,space,space,space,
        rock,space,space,rock,rock,
        rock,rock,space,space,rock,
        space,space,rock,space,rock,
        space,rock,space,space,space,
        space,rock,space,rock,space,
        space,space,rock,space,space,
        space,space,rock,space,space,
        space,rock,rock,space,rock,
        space,space,space,space,rock,
        rock,rock,space,rock,rock,
        rock,space,space,space,space,
        space,space,rock,rock,space,
        space,rock,rock,space,space,
        space,rock,rock,space,rock,
        rock,rock,space,space,space,
        space,space,rock,rock,space,
        rock,space,rock,space,space,
        rock,space,space,space,space,
        rock,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,rock,space,space,
        'finish',rock,rock,space,rock],

        [rock,rock,space,rock,rock,
        space,space,rock,space,rock,
        space,rock,rock,space,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,space,rock,space,space,
        space,space,rock,space,space,
        rock,space,rock,space,space,
        space,space,space,space,rock,
        rock,space,rock,space,rock,
        space,space,space,space,rock,
        space,space,space,rock,rock,
        space,rock,space,space,space,
        rock,space,rock,rock,space,
        rock,space,space,rock,space,
        space,rock,space,space,space,
        space,space,rock,space,space,
        space,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,rock,rock,space,
        space,space,space,rock,space,
        rock,rock,space,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,rock,
        space,space,space,space,player],

        [rock,rock,rock,rock,rock,
        player,space,space,space,space,
        rock,rock,rock,rock,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,rock,rock,rock,space,
        space,rock,space,space,space,
        space,rock,space,space,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,rock,
        space,rock,space,space,space,
        space,rock,rock,rock,space,
        space,rock,space,rock,space,
        space,space,space,space,space,
        space,rock,space,rock,space,
        space,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,space,rock,finish]]
